### ISSUE TITLE
Triggering server thread deadlock

### ISSUE THREAD

**Issue by SAGUMEDREAM** [enjarai/restart-detector#6]
When I placed this kind of block in a certain block before, my server did not respond the next time I entered that chunk, and spark displayed in the background [13:25:38] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics

I modified spark to get the following thread stack
Then I disabled restart-detector and approached that chunk again to restore it to normal

[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]: Thread: Server thread (State: RUNNABLE)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_1255.method_18857(class_1255.java:145)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_3215$class_4212.method_18857(class_3215.java:525)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_3215.method_12121(class_3215.java:137)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_1937.method_8402(class_1937.java:208)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_4538.method_22342(class_4538.java:156)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_1937.method_8497(class_1937.java:202)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_1937.method_8320(class_1937.java:374)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at dev.enjarai.restartdetector.block.TpsDetectorBlock$1.getSpeed(TpsDetectorBlock.java:78)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at dev.enjarai.restartdetector.display.SpinnyHolder.updateSpinny(SpinnyHolder.java:31)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at dev.enjarai.restartdetector.display.SpinnyHolder.<init>(SpinnyHolder.java:23)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at dev.enjarai.restartdetector.block.TpsDetectorBlock$1.<init>(TpsDetectorBlock.java:75)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at dev.enjarai.restartdetector.block.TpsDetectorBlock.createElementHolder(TpsDetectorBlock.java:75)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_2818.handler$ebg001$polymer-virtual-entity$polymer$polymerBlocksInit(class_2818.java:5281)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_2818.<init>(class_2818.java:111)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_2852.method_12395(class_2852.java:166)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_3898.method_43375(class_3898.java:553)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_3898$$Lambda/0x00007fdbf638eae8.apply(Unknown Source)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at java.base@21.0.4/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at java.base@21.0.4/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_1255.method_18859(class_1255.java:162)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:552)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_1255.method_16075(class_1255.java:136)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:561)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_3215.method_19492(class_3215.java:263)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:852)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.class_1255.method_18857(class_1255.java:145)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:23625)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
[13:25:38] [spark-async-sampler-worker-thread/INFO]: [STDOUT]:     at net.minecraft.server.MinecraftServer$$Lambda/0x00007fdbf5f0c3c8.run(Unknown Source)

**Comment by enjarai** [comment]
What mc version does this happen on? Can you provide your full modlist/a full log file where this issue occurs?

**Comment by SAGUMEDREAM** [comment]
> What mc version does this happen on? Can you provide your full modlist/a full log file where this issue occurs?

[2024-11-02-3.log.gz](https://github.com/user-attachments/files/17606961/2024-11-02-3.log.gz)
[2024-11-02-1.log.gz](https://github.com/user-attachments/files/17606965/2024-11-02-1.log.gz)

**Comment by enjarai** [comment]
Interesting... I'm not sure why this issue has never popped up before, but I think I see whats causing it, give me a moment.

**Comment by enjarai** [comment]
Right, could you try with the following dev jar and see if it works?
https://github.com/enjarai/restart-detector/actions/runs/11643578577

**Comment by SAGUMEDREAM** [comment]
> Right, could you try with the following dev jar 和 see if it works?那么，您能否尝试一下以下 dev jar 并查看它是否有效？ https://github.com/enjarai/restart-detector/actions/runs/11643578577

I'm afraid I won't have a chance to try this... My players need a stable server

**Comment by Rozbiynk** [comment]
I previously have same issue on 1.21.1, i think i can test it on fresh install a little bit later
